### ISSUE TITLE
Error while dialing SMTP server: dial tcp :587: getsockopt: connection refused" on pull-request build.

### ISSUE THREAD

**Issue by aliakseimaniuk** [Drillster/drone-email#20]
## Description:
Create pull request. It might be an issue with sending notifications for a pull-request.

> NOTE: My pull request contains Cyrillic symbols, I'm not sure, if it is the main cause of the issue.

## Actual result:
drone-email plugin throws an exception:
```
time="2017-11-20T14:56:01Z" level=error msg="Error while dialing SMTP server: dial tcp :587: getsockopt: connection refused" dial tcp :587: getsockopt: connection refused
exit code 1
```

## Plugin configuration:
```
  notify:
    image: drillster/drone-email
    secrets: [ email_host, email_port, email_username, email_password ]
    from: test@test.com
    recipients: [ user@test.com ]
    when:
      status: [ success, failure ]
```
**email_host**: smtp.gmail.com
**email_port**: 587

**Comment by fridaystreet** [comment]
Also having this issue trying to use smtp.gmail.com which needs port 465. Doesn't look like the port configuration option is taking effect. drone version 0.8

**Comment by mjwwit** [comment]
@aliakseimaniuk I'm sorry for the late response.

Your situation might be related to Drone's dealing with secrets and pull-requests. Are you sure they're getting injected correctly?

**Comment by aliakseimaniuk** [comment]
@mjwwit notifications work properly when I push code to the branch, but seems you are right, secrets are not injected during pull-request. I just checked that $EMAIL_HOST and $EMAIL_PORT are empty during pull request, I assume that the others empty too. 

Do you know if it is a known issue in drone? I use 0.8.0-rc.5 version.

**Comment by mjwwit** [comment]
I think Drone changed the way it deals with secrets for pull-requests. You'll probably find more on this in the Drone docs. Let me know if you can't find what you're looking for.

**Comment by mjwwit** [comment]
@aliakseimaniuk did you manage to fix your issue?

**Comment by mjwwit** [comment]
I'll just assume it's fixed now.

**Comment by vityafx** [comment]
I can't expose email secrets to the plug in, but I can see them printed if I echo them. There must be a problem still in the plug in.

**Comment by mjwwit** [comment]
Can you post your config?

**Comment by vityafx** [comment]
Yes, excuse me, I would do that yesterday as well but I could not.

```yaml
clone:
  git:
    image: plugins/git
    tags: true
    depth: 1

pipeline:
  test-secrets-and-env:
    image: alpine
    secrets: [ email_notification_host, discord_webhook_token ]
    commands:
     - echo $email_notification_host
     - echo ${email_notification_host}
     - echo $$email_notification_host
     - echo $EMAIL_NOTIFICATION_HOST
     - echo $DISCORD_WEBHOOK_TOKEN
     - echo $$DISCORD_WEBHOOK_ID
     - echo $$DISCORD_WEBHOOK_TOKEN
     - echo ${DISCORD_WEBHOOK_ID}
     - echo ${DISCORD_WEBHOOK_TOKEN}
     - echo $CI
     - echo $$CI
     - echo ${CI}
     - echo $DRONE_ARCH
     - echo $$DRONE_ARCH
     - echo ${DRONE_ARCH}
     - echo $DRONE_BRANCH
     - echo $$DRONE_BRANCH
     - echo ${DRONE_BRANCH}
     - echo $DRONE_COMMIT_BRANCH
     - echo $$DRONE_COMMIT_BRANCH
     - echo ${DRONE_COMMIT_BRANCH}
     - echo $DRONE_REPO_BRANCH
     - echo $$DRONE_REPO_BRANCH
     - echo ${DRONE_REPO_BRANCH}
     - env
  notify-email:
    image: drillster/drone-email
    pull: true
    when:
      branch: [ master, testing ]
      event: push
    host: ${EMAIL_NOTIFICATION_HOST}
    port: ${EMAIL_NOTIFICATION_PORT}
    username: ${EMAIL_NOTIFICATION_USERNAME}
    password: ${EMAIL_NOTIFICATION_PASSWORD}
    from: ${EMAIL_NOTIFICATION_FROM}
    secrets: [ email_notification_host, email_notification_port, email_notification_username, email_notification_password, email_notification_from ]

services:
  database:
    image: postgres
    pull: true
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
```

Basically it is as simple as that. The `email_notification_host` variable is shown in the log if I `echo` it but it can't be read by the `email` plugin any way I tried:

```bash
$EMAIL_NOTIFICATION_HOST
$$EMAIL_NOTIFICATION_HOST
${EMAIL_NOTIFICATION_HOST}
# and so on
```

However, exactly the same syntax works everywhere else.

**Comment by vityafx** [comment]
Should I provide you with anything else, @mjwwit?

**Comment by bradrydzewski** [comment]
I see a few issues with the configuration:

All of these lines should be removed:

```diff
  notify-email:
    image: drillster/drone-email
    pull: true
    when:
      branch: [ master, testing ]
      event: push
-   host: ${EMAIL_NOTIFICATION_HOST}
-   port: ${EMAIL_NOTIFICATION_PORT}
-   username: ${EMAIL_NOTIFICATION_USERNAME}
-   password: ${EMAIL_NOTIFICATION_PASSWORD}
-   from: ${EMAIL_NOTIFICATION_FROM}
    secrets: [ email_notification_host, email_notification_port, email_notification_username, email_notification_password, email_notification_from ]

```

When you pass secrets into the plugin you should not also set their attributes directly. In this case you are likely overriding the secrets.

Also your secret names appear to be invalid.  For example the plugin expects a secret named `EMAIL_HOST` as opposed to `EMAIL_NOTIFICATION_HOST`. When you pass secrets to a plugin the variable names are important and must match the expected input of the plugin.  I was able to see a list of all secret variable names by looking at the code, at https://github.com/Drillster/drone-email/blob/master/main.go#L24:L81

**Comment by vityafx** [comment]
> When you pass secrets into the plugin you should not also set their attributes directly.
Oh, I don't remember I saw anything like that mentioned in the docs. Let me try without them and correcting the names to the ones that the plugin expects. Could we also mention these details right on the plugin page please?

**Comment by bradrydzewski** [comment]
The Drone secret documentation does mention this explicitly:

> The names of these secret variables are dictated by the plugin. You should therefore consult the individual plugin documentation to determine the exact secret name that should be used.

> The plugin will look for the named environment variables at runtime. The variable names are therefore important.

This plugin does not seem to document the secret names (at http://plugins.drone.io/drillster/drone-email/). I would encourage the plugin owner (or community member such as yourself) to send a pull request to update the plugin documentation accordingly.

**Comment by mjwwit** [comment]
> This plugin, however, does not seem to document the secret names (at http://plugins.drone.io/drillster/drone-email/). I would encourage the plugin owner (or community member such as yourself) to send a pull request to update the plugin documentation accordingly (at https://github.com/drone/drone-plugin-index).

Sorry, forgot about that. Will add it to my list.

> Looks like it worked, thanks! However, it would also be good to add `EMAIL_FROM` instead of having only `PLUGIN_FROM` secret name (env variable which the plugins reads from).

You can rename secrets like [this](http://docs.drone.io/manage-secrets/#alternate-names).

**Comment by jessequinn** [comment]
I realize this is a closed issue; however, i have the same issue.

```
---
kind: pipeline
type: exec
name: site

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare_production
    commands:
      - cp .env.prod.dist .env
    when:
      branch:
        - master

  - name: prepare_development
    commands:
      - cp .env.dev.dist .env
    when:
      branch:
        - develop

  - name: backend
    commands:
      - composer install

  - name: frontend_development
    commands:
      - yarn install
      - yarn run encore dev
    when:
      branch:
        - develop

  - name: frontend_production
    commands:
      - yarn install
      - yarn run encore production
    when:
      branch:
        - master

  - name: deploy_production
    commands:
      - rm -rf /var/www/jessequinn/*
      - rsync -avz --progress --exclude .git/ . /var/www/jessequinn/
      - chown -R www-data:www-data /var/www/jessequinn
      - find /var/www/jessequinn -type d -exec chmod 755 {} \;
      - find /var/www/jessequinn -type f -exec chmod 644 {} \;
    when:
      branch:
        - master

  - name: deploy_development
    commands:
      - rm -rf /var/www/dev/jessequinn/*
      - rsync -avz --progress --exclude .git/ . /var/www/dev/jessequinn/
      - chown -R www-data:www-data /var/www/dev/jessequinn
      - find /var/www/dev/jessequinn -type d -exec chmod 755 {} \;
      - find /var/www/dev/jessequinn -type f -exec chmod 644 {} \;
    when:
      branch:
        - develop

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: email

steps:
  - name: notify
    image: drillster/drone-email
    environment:
      host:
        from_secret: email_host
      username:
        from_secret: email_username
      password:
        from_secret: email_password
    from: noreply@jessequinn.info
    when:
      status:
        - failure
        - success
      branch:
        - develop
      event:
        - push
        - pull_request

depends_on:
  - site
```

I have also tried `secrets: [ email_username, email_password ]` with failure.

**Comment by jessequinn** [comment]
resolved. problem is yet again the documentation is outdated

```
  - name: notify
    image: drillster/drone-email
    environment:
      EMAIL_HOST:
        from_secret: email_host
      EMAIL_USERNAME:
        from_secret: email_username
      EMAIL_PASSWORD:
        from_secret: email_password
    settings:
      from: noreply@jessequinn.info
      recipients:
        - me@jessequinn.info
    when:
      status:
        - failure
        - changed
      branch:
        - develop
        - master
```

placement of secrets within settings: fixed this
